services:
  db:
    image: mysql:8
    container_name: chattingo-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    image: ${BACKEND_REPO}:${BACKEND_TAG}
    container_name: chattingo-backend
    restart: unless-stopped
    ports:
      - "8085:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      CORS_ALLOWED_METHODS: ${CORS_ALLOWED_METHODS}
      CORS_ALLOWED_HEADERS: ${CORS_ALLOWED_HEADERS}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SERVER_PORT: ${SERVER_PORT}
      WEBSOCKET_ENDPOINT: ${WEBSOCKET_ENDPOINT}
    depends_on:
      - db

  frontend:
    image: ${FRONTEND_REPO}:${FRONTEND_TAG}
    container_name: chattingo-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    env_file:
      - .env
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
      REACT_APP_WS_URL: ${REACT_APP_WS_URL}
      REACT_APP_ENV: ${REACT_APP_ENV}
      REACT_APP_DEBUG: ${REACT_APP_DEBUG}
    depends_on:
      - backend

volumes:
  db_data:   